package com.cromulent.box_timer.presentation.timer_screen

import androidx.compose.animation.animateContentSize
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicText
import androidx.compose.foundation.text.TextAutoSize
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.VerticalDivider
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.backhandler.BackHandler
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Color.Companion.White
import androidx.compose.ui.graphics.Shadow
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import boxtimerpro.composeapp.generated.resources.Res
import boxtimerpro.composeapp.generated.resources.back_ic
import boxtimerpro.composeapp.generated.resources.button_continue
import boxtimerpro.composeapp.generated.resources.button_pause
import boxtimerpro.composeapp.generated.resources.button_reset
import boxtimerpro.composeapp.generated.resources.button_resume
import boxtimerpro.composeapp.generated.resources.button_start
import boxtimerpro.composeapp.generated.resources.button_stop_exit
import boxtimerpro.composeapp.generated.resources.dialog_timer_running_message
import boxtimerpro.composeapp.generated.resources.dialog_timer_running_title
import boxtimerpro.composeapp.generated.resources.header_subtitle_ready_to_train
import boxtimerpro.composeapp.generated.resources.header_title_app
import com.cromulent.box_timer.core.util.formatTime
import com.cromulent.box_timer.presentation.components.Header
import com.cromulent.box_timer.presentation.theme.BoxTimerProThemePrv
import com.cromulent.box_timer.presentation.theme.FireDarkColorScheme
import com.cromulent.box_timer.presentation.theme.FireLightColorScheme
import com.cromulent.box_timer.presentation.theme.ForestDarkColorScheme
import com.cromulent.box_timer.presentation.theme.ForestLightColorScheme
import com.cromulent.box_timer.presentation.theme.IceDarkColorScheme
import com.cromulent.box_timer.presentation.theme.IceLightColorScheme
import com.cromulent.box_timer.presentation.theme.MidnightDarkColorScheme
import com.cromulent.box_timer.presentation.theme.MidnightLightColorScheme
import com.cromulent.box_timer.presentation.theme.NeonDarkColorScheme
import com.cromulent.box_timer.presentation.theme.NeonLightColorScheme
import com.cromulent.box_timer.presentation.theme.OceanDarkColorScheme
import com.cromulent.box_timer.presentation.theme.OceanLightColorScheme
import com.cromulent.box_timer.presentation.theme.PrincessPinkDarkColorScheme
import com.cromulent.box_timer.presentation.theme.PrincessPinkLightColorScheme
import com.cromulent.box_timer.presentation.theme.RoyalDarkColorScheme
import com.cromulent.box_timer.presentation.theme.RoyalLightColorScheme
import com.cromulent.box_timer.presentation.theme.SecondarySubtitleColor
import com.cromulent.box_timer.presentation.theme.ShadowDarkColorScheme
import com.cromulent.box_timer.presentation.theme.ShadowLightColorScheme
import com.cromulent.box_timer.presentation.theme.SunsetDarkColorScheme
import com.cromulent.box_timer.presentation.theme.SunsetLightColorScheme
import com.cromulent.box_timer.presentation.theme.VenomDarkColorScheme
import com.cromulent.box_timer.presentation.theme.VenomLightColorScheme
import com.cromulent.box_timer.presentation.timer_screen.components.Chip
import com.cromulent.box_timer.presentation.timer_screen.components.RectangleButton
import com.cromulent.box_timer.presentation.timer_screen.components.TimerCircleIndicator
import compose.icons.FontAwesomeIcons
import compose.icons.fontawesomeicons.Solid
import compose.icons.fontawesomeicons.solid.Exclamation
import kotlinx.coroutines.flow.MutableStateFlow
import org.jetbrains.compose.resources.painterResource
import org.jetbrains.compose.resources.stringResource
import org.jetbrains.compose.ui.tooling.preview.Preview

@OptIn(ExperimentalComposeUiApi::class)

@Composable
expect fun TimerScreenRoot(
    viewModel: TimerViewModel,
    closeTimerScreen: () -> Unit,
    modifier: Modifier = Modifier
)